import React, { useState } from 'react';

export const PrivacyPolicy: React.FC = () => {
    const [isOpen, setIsOpen] = useState(false);

    const handleToggle = (e: React.MouseEvent) => {
        e.preventDefault();
        setIsOpen(!isOpen);
    };

    return (
        <>
            <a href="#" onClick={handleToggle} className="hover:text-purple-400 transition-colors">
                Privacy Policy
            </a>

            {isOpen && (
                <div 
                    className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 animate-[fade-in_0.2s_ease-out]"
                    onClick={() => setIsOpen(false)}
                >
                    <div 
                        className="bg-slate-800 border border-slate-700 rounded-lg p-8 max-w-md w-full m-4 shadow-2xl"
                        onClick={e => e.stopPropagation()}
                    >
                        <h3 className="text-xl font-bold text-slate-100 mb-4">Privacy & Data Handling</h3>
                        <div className="text-slate-300 space-y-4">
                            <p>We are committed to your privacy. This application operates entirely in your browser.</p>
                            <p>
                                <strong className="text-slate-100">We do not store, save, or log any of your data.</strong> 
                                The product descriptions you enter and the content generated by the AI are processed in memory and are never sent to our servers or any third-party databases.
                            </p>
                            <p>Once you close the browser tab, the information is gone forever. Your ideas remain your own.</p>
                        </div>
                        <button 
                            onClick={() => setIsOpen(false)}
                            className="mt-6 w-full px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white font-bold rounded-lg transition-colors"
                        >
                            Got it!
                        </button>
                    </div>
                </div>
            )}
        </>
    );
};
